# GitHub Action for compiling LaTeX documents
name: Compile LaTeX

# Controls when the action will run.
# This workflow runs on pushes to the 'main' branch.
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "compile_latex"
  compile_latex:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout Repo
      uses: actions/checkout@v4

    # Sets up the Tectonic typesetting system
    - name: Setup Tectonic
      uses: wtfjoke/setup-tectonic@v3
        # You can specify a Tectonic version, or leave it for the latest
        # tectonic-version: '0.14.1'

    # Compiles the LaTeX file.
    # Replace 'main.tex' with the name of your main LaTeX file.
    - name: Compile LaTeX
      run: tectonic -X build

    # Optional: Upload the compiled PDF as an artifact
    # The PDF will be available for download from the Actions tab of your repository.
    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: compiled-pdf
        path: coding-theory.pdf # Make sure this matches the output file name
